##################################################################################################
# products
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
    service: products
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: products
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products
  labels:
    account: products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-v1
  labels:
    app: products
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
      version: v1
  template:
    metadata:
      labels:
        app: products
        version: v1
    spec:
      serviceAccountName: products
      containers:
      - name: products
        image: gcr.io/nodal-formula-295821/openbasket/product-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080